### ISSUE TITLE
Split integration test

### ISSUE THREAD

**Issue by bohai** [docker/libcompose#56] opened 2015-09-23 03:28 UTC
Now all the integration tests are in `basic_test.go`, it's no clear.
I want to split tests by command, so that we can enhance every command test in their own file.

**Comment by bohai** [comment] 2015-09-23 03:28
ping @aanand @aduermael @ibuildthecloud @gdevillele
WDYT?

**Comment by ibuildthecloud** [comment] 2015-09-23 03:32
+1

The tests ended up that way largely due to my laziness, I wasn't sure how to separate the tests into different files w/ go-check so I just didn't do anything :disappointed:

**Comment by vdemeester** [comment] 2015-09-23 06:32
@bohai good idea, was on my todo list for a while :stuck_out_tongue_closed_eyes:.

The question is then how to split them : by commands (like `up`, `kill`, etc..) or ?

**Comment by dnephin** [comment] 2015-09-23 14:24
We'd like to extract the cli test suite from `docker-compose` and have it run by executing the binary. That way we can use the same test suite against libcompose and ensure at least partial feature parity (for the areas covered by test). 

So I'd suggest keeping the testing to more of the internals, instead of working on the end-to-end tests for each command.

**Comment by vdemeester** [comment] 2015-09-23 14:30
@dnephin :+1: :wink:

**Comment by ibuildthecloud** [comment] 2015-09-23 14:37
@dnephin I don't think I really agree for the short term.  I can't imagine you will port the Python test soonish.  I'm a strong believer that integration tests are more valuable that unit tests.  So I'd prefer we continue on the current path of how we write tests so libcompose can continue forward.

Split the tests into files by command (up, kill, etc) seems logical to me.

**Comment by dnephin** [comment] 2015-09-23 14:53
> Split the tests into files by command (up, kill, etc) seems logical to me.

Yes, I agree that's a good idea, I was just putting it out there so that no one spends a bunch of time adding test coverage that may be replaced by a shared suite.  Adding a few additional tests while things are being developed seems fine to me.

>  I'm a strong believer that integration tests are more valuable that unit tests.

I think it would be good to clarify terminology here. Integration testing is whitebox testing of multiple components together.

What is currently in `integration/` is much closer to end-to-end blackbox testing, often called acceptance testing, functional testing, or system testing.

I think both are very important. Unit tests are important for the developer to be able to iterate quickly and have confidence in the individual functions and internal design.  end-to-end tests are important for the overall quality of the product to catch regressions and changes in behaviour.  Which is why I think a shared test suite is so important. We can't make a claim that the packages are equivalent without having a test suite that verifies it.

**Comment by bohai** [comment] 2015-09-24 03:20
@vdemeester: 
Yeah, by commands is OK (like `swarm`).
 I have  split it locally and will submit a PR. :)

**Comment by vdemeester** [comment] 2015-10-17 21:13
Closing this one #57 is merged.

**Closed by vdemeester** 2015-10-17 21:13 UTC
