### ISSUE TITLE
libcompose should be go gettable/buildable/testable

### ISSUE THREAD

**Issue by aluzzardi** [docker/libcompose#32] opened 2015-08-17 22:55 UTC
As documented, the build and test process are currently driven by a `Makefile` performing actions in a container.

Since this is a library, it should be `go gettable/buildable/testable` out of the box without having to run a non-standard process.

There are apparently dependencies against non-pkg parts of docker which make it tricky to do so.

**Comment by ibuildthecloud** [comment] 2015-08-17 23:44
This custom makefile is just to use a DIND setup to build and test.  Besides the fact that this code is using non-pkg docker, it should be compatible with go get.  The non-pkg code needs to be resolved by pulling that code out of docker and into a separate project.  Which I believe is being worked on for 1.9.

**Comment by aluzzardi** [comment] 2015-08-17 23:56
I think the main offender is the `github.com/docker/docker/registry` import in `docker/container.go`.

That's preventing me to build a "hello world" using `libcompose`:

```
$ go build
../../docker/docker/registry/registry.go:21:2: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/local/go/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/root/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
```

Other than that, this is pretty awesome!

**Comment by ibuildthecloud** [comment] 2015-08-18 00:07
This is related to https://github.com/docker/docker/issues/11699.  I don't know if that issue is going to ever be resolved.  I'd guess the official solution would be "don't import that package."  So this goes back to the fact this code is uses non-pkg code from Docker.  The offending packages are:

```
github.com/docker/docker/cliconfig
github.com/docker/docker/opts
github.com/docker/docker/api
github.com/docker/docker/utils
github.com/docker/docker/graph/tags
github.com/docker/docker/runconfig
```

We can probably go through and start removing the dependency on these but the majority of the reason that the code is imported is because this library has to duplicate the same logic.  @icecrime This is in part why I'm really interested in working on the server/client API project.  A lot of "util" code should move there also.

**Comment by vdemeester** [comment] 2015-08-18 07:36
@ibuildthecloud The more *problematic* package on the list are `runconfig` and `registry. The server/client API project should definitely help resolving this issue, but it will depend what will be there.

On the long term the server/client API should help a lot to remove duplication. On the short term, there is a few package dependencies that we can remove (by duplicating the code a bit).

**Comment by ibuildthecloud** [comment] 2015-08-22 06:43
I hate duplicating code.  Maybe an incremental step would be to start putting in PRs to docker engine to move more common functionality to pkg.

**Comment by ibuildthecloud** [comment] 2015-10-07 19:57
@vdemeester Do you have any suggestions on how we can tackle this?  I'm wondering if we can maybe break this up into chunks of works.  I know there are people willing to work on it but this effort is vague and daunting.  The fact that libcompose is not `go gettable` seems like a pretty big problem.

**Comment by vdemeester** [comment] 2015-10-07 20:21
@ibuildthecloud Yes I aslo think we should break this into chunks of works. I'm not gonna be available tomorrow but I'll try to create a list of things that can (or cannot) be done in parallel in smaller chunks so that we can track the progress too :smile_cat:

**Comment by vdemeester** [comment] 2015-10-11 14:28
## TODO

*WIP* : I'll complete this and create issue this evening :wink: 

- `github.com/docker/docker/utils` : 
  - `ReadDockerIgnore`
  - `ValidateContextDirectory`
  - `ImageReference`

- `github.com/docker/docker/registry` :
  - `ParseRepositoryInfo`
  - `ResolveAuthConfig`

## Handled

- `github.com/docker/docker/runconfig`:
  - `runconfig.Config` should be handled by #71 ([here](https://github.com/fsouza/go-dockerclient/blob/2bd40eb3ca54e74e8181ecbbc9b91902cb03d1df/container.go#L187))
- `github.com/docker/docker/cliconfig` : call is on `ConfigDir` and `Load`, this is needed to get the folder where certificates are & co (to communicate with the API). Maybe handled by #71 too.

- `github.com/docker/docker/api` : call is limited to `api.DefaultDockerfileName`, I think it's safe to use `Dockerfile` directly. *(PR to follow)*
- `github.com/docker/docker/graph/tags` : call is limited to `tags.DEFAULTTAG`, same as `api`, safe to use `latest` directly. *(PR to follow)*

## NOT TODO

- `github.com/docker/docker/opts` : shouldn't be too much of a problem, do not import the autogen stuff, so can be ignored (used the same way in fsouza/go-dockerclient).

**Comment by ibuildthecloud** [comment] 2015-10-11 15:10
Wow, maybe this is easier than I thought :smile:

**Comment by flower-pot** [comment] 2015-10-18 21:14
Shouldn't #78 be a nice step towards this?

**Comment by gondor** [comment] 2015-11-08 16:00
This is getting close with your recent changes in #83 .  The issue is the needed `go generate` step.  Any chance you couldn't do this and checkin the docker/autogen/dockerversion the go generate creates into the vendor like everything else?

Being dependent on libcompose I was forced to navigate to libcompose in my $GOPATH run `go generate` and then things were ok.   This seems like the last fix needed

**Comment by vdemeester** [comment] 2015-11-08 16:26
@gondor you are right, we could check in the `dockerversion` :stuck_out_tongue_closed_eyes:

**Closed** 2015-12-02 15:59 UTC
